title: Outside The Dining Hall
email: outsidethedininghall@gmail.com
description: >-
  A Variety Show style podcast between two roommates and best friends who think they are way funnier than they are.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: RealSeanAndNick
youtube_username: channel/UCAybLSoP4buQ_Rq3Cbw4U9A

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed