title: Outside the Dining Hall
email: outsidethedininghall@gmail.com
description: > 
  A Variety Show
 baseurl: ''
 twiter_username: RealSeanandNick
 youtube_username: OutsideTheDiningHall
 
 markdown: kramdown
